schemaVersion: 2.1.0
attributes:
  controller.devfile.io/storage-type: per-workspace
metadata:
  name: home-library
projects:
- name: project-main
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/cgruver/che-demo-app.git
- name: ui
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/cgruver/che-demo-app-ui.git
- name: backend
  git:
    checkoutFrom:
      remote: origin
      revision: main
    remotes:
      origin: https://github.com/cgruver/che-demo-app-service.git
components:
- name: dev-tools
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryRequest: 1Gi
    memoryLimit: 6Gi
    cpuRequest: 500m
    cpuLimit: 2000m
    mountSources: true
    sourceMapping: /projects
    env:
    - name: SHELL
      value: "/bin/zsh"
    - name: TESTCONTAINERS_RYUK_DISABLED
      value: "true"
    - name: TESTCONTAINERS_CHECKS_DISABLE
      value: "true"
    - name: DOCKER_HOST
      value: "tcp://127.0.0.1:2475"
    volumeMounts:
    - name: m2
      path: /home/user/.m2
- name: quarkus-runner
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryLimit: 1Gi
    mountSources: true
    sourceMapping: /projects
    volumeMounts:
      - name: m2
        path: /home/user/.m2
    endpoints:
      - name: http-quarkus
        targetPort: 8080
      - exposure: none
        name: debug
        targetPort: 5858
    env:
      - name: DEBUG_PORT
        value: '5858'
      - name: JAVA_HOME 
        value: /etc/alternatives/jre_17
    args:
      - '-f'
      - /dev/null
    command:
      - tail
- name: node-runner
  container: 
    image: quay.io/cgruver0/che/che-demo-app:latest
    memoryLimit: 1Gi
    mountSources: true
    sourceMapping: /projects
    endpoints:
      - name: node
        targetPort: 4000
    args:
      - '-f'
      - /dev/null
    command:
      - tail
- name: postgres
  container:
    image: quay.io/sclorg/postgresql-15-c9s:c9s
    memoryLimit: 512M
    sourceMapping: /projects
    mountSources: true
    env:
    - name: POSTGRESQL_USER
      value: postgres
    - name: POSTGRESQL_PASSWORD
      value: postgres
    - name: POSTGRESQL_DATABASE
      value: postgres
    volumeMounts:
    - name: pgdata
      path: /var/lib/pgsql/data
- name: oc-cli
  container:
    args:
      - '-f'
      - /dev/null
    command:
      - tail
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    sourceMapping: /projects
    mountSources: true
    memoryLimit: 64M
- volume:
    size: 4Gi
  name: projects
- volume:
    size: 2Gi
  name: m2
- volume:
    size: 2Gi
  name: pgdata
commands:
  - id: init-workspace
    exec:
      component: tools
      commandLine: 'bash...'
      workingDir: ${PROJECT_SOURCE}
  - id: dev-run
    exec:
      component: tools
      commandLine: 'mvn -Dmaven.repo.local=/home/user/.m2/repository quarkus:dev -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager'
      hotReloadCapable: true
      group:
        kind: run
        isDefault: true
      workingDir: ${PROJECT_SOURCE}
  - id: dev-debug
    exec:
      component: tools
      commandLine: 'mvn -Dmaven.repo.local=/home/user/.m2/repository quarkus:dev -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Ddebug=${DEBUG_PORT}'
      hotReloadCapable: true
      group:
        kind: debug
        isDefault: true
      workingDir: ${PROJECT_SOURCE}
events:
  postStart:
    - init-compile